#配置中心地址
spring:
  cloud:
    config:
      label: gateway
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  #      routes:
#      - id: client
#        uri: lb://CLIENT
#        predicates:
#          - Path=/client/**
#        filters:
#          - StripPrefix=2
  #应用名称
  application:
    name: gateway
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
#应用端口
server:
  port: 8888
ip-address: 127.0.0.1