#####配置中心#####
spring:
  application:
    name: config
  security:
    user:
      name: branch
      password: spdb1234
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties,classpath:/properties/client,classpath:/properties/gateway
#配置中心端口
server:
  port: 7777
ip-address: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${ip-address}
    instance-id: ${ip-address}:${server.port}
##忽略权限拦截
management:
  security:
    enabled: false